query blogposts {
  blogposts(
    sort: "DateWritten:desc" # Sort by DateWritten in descending order
  ) {
    documentId
    Title
    Author
    DateWritten
    Slug
    Image {
      url
      alternativeText
    }
    PostBodyPreview
  }
}
