query blogposts {
  blogposts(
    sort: "DateWritten:desc" # Sort by DateWritten in descending order
    pagination: { page: 1, pageSize: 4 } # Limit to 4 results
    filters: { publishedAt: { not: null } }
  ) {
    documentId
    Title
    Author
    DateWritten
    Slug
    Image {
      url
      alternativeText
    }
    PostBodyPreview
  }
}
